UMBRAL_OCUPACION_ALTA = 80
UMBRAL_MANTENIMIENTO_ATRASADO = 120
UMBRAL_LLUVIA_INTENSA = 40

UMBRAL_OCUPACION_CRITICA = 95
UMBRAL_MANTENIMIENTO_CRITICO = 180

PESO_OCUPACION = 2
PESO_MANTENIMIENTO = 3
PESO_LLUVIA = 3

MAX_VERDE = 2
MAX_AMARILLO = 5

# Criterio preventivo del prototipo: acumulado de tres días, no límite normativo.
UMBRAL_PRECIPITACION_ACUMULADA_MM = 40
VERSION_REGLAS_CLIMA = "clima-v1"
